# Generated by Django 6.1.1 on 2026-09-24 18:21

import django.core.validators
import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#fef08a', help_text='Hex code of the note color from the allowed palette.', max_length=20, validators=[notes.models.validate_note_color])),
                ('x', models.IntegerField(default=100, help_text='X coordinate in pixels on the note board.', validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(default=100, help_text='Y coordinate in pixels on the note board.', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['id'],
            },
        ),
    ]
