# Generated by Django 6.1.1 on 2026-09-24 19:05

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(default='#ffdd67', help_text='Hex code of the note color from the allowed palette.', max_length=20, validators=[notes.models.validate_note_color]),
        ),
    ]
